### ISSUE TITLE
Create the payment controller

### ISSUE THREAD

**Issue by timalts** [timalts/captain-moodle#11]
Create the payment controller with all the necessary endpoints:
🪧Don't forget to scaffold the controller from the model first !
- [Role = Admin] : GET - get_all() - Fetch all the payment in the table
- [Role = Admin, Student] : GET - get_byuserid() - Fetch all the payment for a specific user id and if requested by a student, his id must match the one he's requesting for (You can fetch the user role using UserManager)
- [Role = Admin, Student] : POST - add_payment() - Add a payment for a specific user and if request by a student, his id must match the one he's request for
- [Role = Admin] : DELETE - delete_payment() - Delete a payment
- [Role = Admin] : PUT - edit_payment() - Edit a payment

**Comment by plgarnerone** [comment]
Controller created

**Comment by timalts** [comment]
I changed the POST request used for the Create view so it add the id of the user who is trying to post a new payment in the db

**Comment by timalts** [comment]
Done.
