### ISSUE TITLE
Whole authentication and roles implementation

### ISSUE THREAD

**Issue by xyo-toy** [timalts/captain-moodle#5]
Setup access level when login

**Comment by timalts** [comment]
I added the beginning of the auth system so I can work on the setting up the access level when logging in now

**Comment by xyo-toy** [comment]
-Login and register done by Timalts
-Role management  done by Emeric

**Comment by xyo-toy** [comment]
@timalts May you create a new branch to merge authentication base project and the current projet ?

**Comment by timalts** [comment]
> @timalts May you create a new branch to merge authentication base project and the current projet ?

Done. The name is `auth`
